- src/metric.rs
- src/node.rs
- src/recorders/hdf.rs
- src/recorders/mod.rs
- src/schema/nodes/mod.rs
- src/schema/nodes/piecewise_storage.rs
- src/schema/test_models/piecewise_storage1.json
- src/schema/test_models/piecewise_storage2.json
This is a working prototype of a PiecewiseStorage node that includes multiple internal stores. There is a basic unit test but limited functionality (e.g. no min volume, initial volume, or cost on the upper residual store).
> feat: Add initial implementation of PiecewiseStorage.

- Cargo.toml
- src/schema/parameters/data_frame.rs
Hello,
When compiling the `polars-core` crate with `maturin`, the build fails. The problem does not occur after updating to `polars-0.32.0`. 
However the new version changed the signature of `to_ndarray` which is used in the `DataFrameParameter`. The function is now properly called with the `IndexOrder::default()` parameter (Fortran). This is the same behaviour in 0.30.0.
> Cannot compile polars-core-0.30.0

- src/lib.rs
- src/model.rs
- src/parameters/activation_function.rs
- src/parameters/constant.rs
- src/parameters/mod.rs
- src/parameters/offset.rs
- src/parameters/vector.rs
- src/schema/mod.rs
- src/schema/model.rs
- src/schema/parameters/aggregated.rs
- src/schema/parameters/core.rs
- src/schema/parameters/doc_examples/aggregated_1.json
- src/schema/parameters/doc_examples/constant_simple.json
- src/schema/parameters/doc_examples/constant_variable.json
- src/schema/parameters/doc_examples/offset_simple.json
- src/schema/parameters/doc_examples/offset_variable.json
- src/schema/parameters/mod.rs
- src/schema/parameters/offset.rs
- src/test_utils.rs
- New VariableParameter trait.
- New methods on Parameter trait to return access variable properties.
- Basic implementation for ConstantParameter.
- Improved ConstantParameter documentations.
- Integrated activation functions into constant parameter.
TODO
> feat: Initial commit of variable API.

- pywr-core/src/derived_metric.rs
- pywr-core/src/lib.rs
- pywr-core/src/metric.rs
- pywr-core/src/model.rs
- pywr-core/src/node.rs
- pywr-core/src/parameters/control_curves/mod.rs
- pywr-core/src/parameters/control_curves/volume_between.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/parameters/py.rs
- pywr-core/src/parameters/rhai.rs
- pywr-core/src/recorders/csv.rs
- pywr-core/src/recorders/hdf.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/state.rs
- pywr-schema/src/nodes/piecewise_storage.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/polynomial.rs
- pywr-schema/src/test_models/piecewise_storage2.json
A derived metric is updated after solve and is for values that could be dependent on state AND paramter values. These need updating and storing for use between time-steps.
Adds a test for piecewise storage model that shows how the volume is updated at the end of time-step, and the derived proportional volume is calculated and retained for use in the next time-step despite the max volumes being updated.
Fixes #63.
> feat: Initial commit of DerivedMetric

- Cargo.toml
- pywr-core/src/lib.rs
- pywr-core/src/parameters/array.rs
- pywr-core/src/parameters/control_curves/interpolated.rs
- pywr-core/src/parameters/control_curves/mod.rs
- pywr-core/src/parameters/control_curves/piecewise.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/discount_factor.rs
- pywr-core/src/parameters/interpolate.rs
- pywr-core/src/parameters/interpolated.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/test_utils.rs
- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/data_tables/scalar.rs
- pywr-schema/src/data_tables/vec.rs
- pywr-schema/src/error.rs
- pywr-schema/src/model.rs
- pywr-schema/src/parameters/control_curves.rs
- pywr-schema/src/parameters/core.rs
- pywr-schema/src/parameters/data_frame.rs
- pywr-schema/src/parameters/discount_factor.rs
- pywr-schema/src/parameters/interpolated.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/profiles.rs
- pywr-schema/src/parameters/tables.rs
Required implementing several new parameters:
- InterpolatedParameter
- DiscountFactorParameter
- DataFrameParameter
Conversion from Storage, Deficit and Flow parameters is now returns an error as these should become metrics in pywr-next.
Todos are left for HydropowerTarget, RollingMeanFlowNode and ScenarioWrapper parameter.
Also the control curve interpolated parameter was renamed due to a naming conflict with InterpolatedParameter.
> feat: Upgrade to pywr-v1-schema v0.8.0.

- pywr-core/src/lib.rs
- pywr-core/src/model.rs
- pywr-core/src/node.rs
- pywr-core/src/virtual_storage.rs
- pywr-schema/src/nodes/annual_virtual_storage.rs
- pywr-schema/src/nodes/monthly_virtual_storage.rs
- pywr-schema/src/nodes/virtual_storage.rs
Virtual storage nodes now add a reference to their linked flow nodes. Those nodes now include an function that aggregates over the local cost and the costs of any linked virtual storage nodes.
There's currently no method to change the default aggregation function from "max" via the schema.
> feat: Initial implementation of virtual storage costs.

- Cargo.toml
- pywr-core/Cargo.toml
This is not ideal, but the current release is very old and difficult to build sometimes.
This also re-enables the zlib feature for handling compressed files.
> chore: Use main version of hdf5 crate.

- .github/workflows/deploy-book.yml
- Cargo.toml
- pywr-book/book.toml
- pywr-book/src/SUMMARY.md
- pywr-book/src/getting_started.md
- pywr-book/src/installation.md
- pywr-book/src/licensing.md
- pywr-python/Cargo.toml
Add basic Getting started instructions.
> docs: Add GitHub action to deploy book to pages.

- clp-sys/Cargo.toml
This might be the cause of some CI failures by using too many resources.
> chore: Disable parallel feature in cc crate

- pywr-core/src/network.rs
- pywr-core/src/parameters/py.rs
- pywr-core/src/parameters/rhai.rs
- pywr-core/src/state.rs
`State::new` contained a lot of similarly typed arguments. This commit removes `State::new` and replaces it with a `StateBuilder` type that contains methods for adding optional arguments (which default to zero) and `.build()` for creating a `State`.
> feat: Add StateBuilder for construction of State

- Cargo.toml
- pywr-schema-macros/Cargo.toml
- pywr-schema-macros/src/lib.rs
- pywr-schema/Cargo.toml
- pywr-schema/src/nodes/annual_virtual_storage.rs
- pywr-schema/src/nodes/core.rs
- pywr-schema/src/nodes/delay.rs
- pywr-schema/src/nodes/loss_link.rs
- pywr-schema/src/nodes/mod.rs
- pywr-schema/src/nodes/monthly_virtual_storage.rs
- pywr-schema/src/nodes/piecewise_link.rs
- pywr-schema/src/nodes/piecewise_storage.rs
- pywr-schema/src/nodes/river.rs
- pywr-schema/src/nodes/river_gauge.rs
- pywr-schema/src/nodes/river_split_with_gauge.rs
- pywr-schema/src/nodes/rolling_virtual_storage.rs
- pywr-schema/src/nodes/virtual_storage.rs
- pywr-schema/src/nodes/water_treatment_works.rs
This contains a derive macro that implements `parameters` and `parameters_mut` methods for nodes.
> feat: add pywr-schema-macro crate

- pywr-core/src/parameters/py.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/python.rs
- pywr-schema/src/test_models/test_parameters.py
This supports using PyParameter as an index parameter with updated schema to define the return type of the Python method.
> feat: Implement Parameter<usize> for PyParameter.

- .github/workflows/linux.yml
- pywr-core/Cargo.toml
- pywr-core/src/solvers/builder.rs
- pywr-core/src/solvers/highs/settings.rs
Restores some removed functions required for the highs solver. Adds highs feature to CI.
> fix: Fix and upgrade highs_sys to v1.6.2

- pywr-core/src/lib.rs
- pywr-core/src/metric.rs
- pywr-core/src/network.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/state.rs
- pywr-schema/src/parameters/aggregated.rs
- pywr-schema/src/parameters/asymmetric_switch.rs
- pywr-schema/src/parameters/control_curves.rs
- pywr-schema/src/parameters/core.rs
- pywr-schema/src/parameters/data_frame.rs
- pywr-schema/src/parameters/delay.rs
- pywr-schema/src/parameters/discount_factor.rs
- pywr-schema/src/parameters/indexed_array.rs
- pywr-schema/src/parameters/interpolated.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/offset.rs
- pywr-schema/src/parameters/polynomial.rs
- pywr-schema/src/parameters/profiles.rs
- pywr-schema/src/parameters/tables.rs
- pywr-schema/src/parameters/thresholds.rs
This removes `IndexParameterIndex` (awful name!) and `MultiValueParameterIndex` in favour of a generic `ParameterIndex<T>.` Where `T` is the return type of the associated `Parameter<T>`. This ensures there is stronger type constraints to prevent using the wrong index in the wrong vec of parameters.
> refactor: Make ParameterIndex generic

- pywr-cli/src/main.rs
- pywr-core/src/parameters/py.rs
- pywr-schema/src/model.rs
Alter the framework for the convert command to capture all the conversion errors and log them to the user.
> feat: Capture conversion errors when using convert CLI.

- pywr-core/src/recorders/metric_set.rs
The issue was caused by the lazy evaluation of `.map()` when collecting into an `Option`. This is now done explicitly.
> fix: Fix an issue accumulating aggregated metric values.

- .github/workflows/python.yml
- pywr-python/Cargo.toml
- pywr-python/src/lib.rs
Enable the "abi3-py39" feature in PyO3. This will now build ABI3 compatible wheels for Python 3.9 and above. Doing this reduces the need for separate builds for each Python version, and therefore reduces the number of CI jobs.
> build: Build Python 3.9 ABI3 wheels.

- pywr-schema/src/metric.rs
- pywr-schema/src/nodes/virtual_storage.rs
Update virtual storage node names to use NodeReference rather than String. #164
> Use NodeReference in VirtualStorage

- Cargo.toml
- pywr-core/src/lib.rs
- pywr-core/src/timestep.rs
- pywr-schema/src/timeseries/align_and_resample.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/src/timeseries/polars_dataset.rs
Main change is to switch to using milliseconds as the main unit for comparison and resampling. polars is also updated to v0.40.0
> feat: updates to use of durations when resampling and aligning timeseries 

- pyproject.toml
- pywr-core/Cargo.toml
- pywr-core/src/aggregated_node.rs
- pywr-core/src/network.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/solvers/cbc/mod.rs
- pywr-core/src/solvers/cbc/settings.rs
- pywr-core/src/solvers/clp/mod.rs
- pywr-core/src/solvers/highs/mod.rs
- pywr-core/src/solvers/mod.rs
- pywr-core/src/test_utils.rs
- pywr-core/src/virtual_storage.rs
- pywr-schema/src/model.rs
- pywr-schema/src/nodes/delay.rs
- pywr-schema/src/nodes/piecewise_link.rs
- pywr-schema/src/nodes/piecewise_storage.rs
- pywr-schema/src/nodes/river_gauge.rs
- pywr-schema/src/nodes/river_split_with_gauge.rs
- pywr-schema/src/nodes/rolling_virtual_storage.rs
- pywr-schema/src/nodes/water_treatment_works.rs
- pywr-schema/src/timeseries/align_and_resample.rs
- pywr-schema/src/timeseries/mod.rs
The current CBC C interface does not support modifying constraint coefficients. Therefore this solver can not support aggregated nodes with factors at present. In theory it could support constant factors, but that is also not implemented here. 
If this initial version is OK there are two follow-ups to come:
1. Refactor #198 to work with CBC as well.
2. Use an updated version of CBC that supports constraint coefficient modification.
> Initial implementation of CBC solver.

- pywr-core/src/virtual_storage.rs
> fix: Assert virtual storage volume in basic test.

- pywr-core/src/lib.rs
- pywr-core/src/models/multi.rs
> feat: Add check for duplicate name when adding a network.

- pywr-schema/src/nodes/river_gauge.rs
This is functionality that is available in Pywr v1.x. Includes conversion from Pywr v1.x "cost" field.
> feat: Add support for bypass cost in RiverGaugeNode.

- .github/workflows/linux.yml
- ipm-ocl/src/lib.rs
- pywr-cli/Cargo.toml
- pywr-cli/src/main.rs
- pywr-core/src/network.rs
- pywr-python/Cargo.toml
- pywr-python/src/lib.rs
- pywr-schema/Cargo.toml
Fix several issues regarding features that Clippy raised. Extends Clippy coverage to all crates except `ipm-simd`, which only works on nightly.
Unifies the solver features to `pywr-cli`, `pywr-schema` and `pywr-python` crates. These enable their dependent crate features as required.
> feat: Unify solver features and fix Clippy issues.

- pywr-schema/src/nodes/core.rs
- pywr-schema/src/test_models/mutual-exclusivity1.json
- pywr-schema/src/test_models/mutual-exclusivity2.json
- pywr-schema/src/test_models/mutual-exclusivity3.json
This matches the attribute name used in core
> chore: rename aggregate node factor attribute to relationship

- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/thresholds.rs
This implementation can use any metric for the value and threshold.
Fixes #146.
> refactor: Rename ParameterThresholdParameter to ThresholdParameter.

- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/data_tables/scalar.rs
- pywr-schema/src/data_tables/vec.rs
- pywr-schema/src/error.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/model.rs
- pywr-schema/src/parameters/mod.rs
- More informative error message when failing to load a table reference.
- Implement loading array data with column headers.
> feat: Data table improvements

- .github/workflows/linux.yml
- .github/workflows/windows.yml
- Cargo.toml
Limit the number of threads in the Linux CI. Disable debuginfo and incremental compilation to save space.
> ci: CI performance improvements & disable debuginfo

- pywr-core/src/derived_metric.rs
- pywr-core/src/node.rs
- pywr-core/src/solvers/builder.rs
- pywr-core/src/solvers/cbc/mod.rs
- pywr-core/src/solvers/clp/mod.rs
- pywr-core/src/solvers/highs/mod.rs
- pywr-core/src/state.rs
- pywr-core/src/virtual_storage.rs
This accounts for small floating point rounding errors and tolerances from LP results. In some cases the resulting volume will be a rounding error above or below the bounds.
This also replicates behaviour from v1.
> fix: Clamp storage volumes to be within min & max volume ranges.

- pywr-core/src/metric.rs
- pywr-core/src/network.rs
- pywr-schema/src/edge.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/model.rs
- pywr-schema/src/nodes/piecewise_link.rs
- pywr-schema/src/test_models/piecewise-link1-edges.csv
- pywr-schema/src/test_models/piecewise-link1-nodes.csv
- pywr-schema/src/test_models/piecewise_link1.json
A new schema and core level metric for returning edge flows. The schema level metric returns core a metric that covers the case where multiple core edges are created from a single schema edge.
Includes some additional tests for picewise-link1.json. This covers the case described above.
> feat: Add Edge metric

- pywr-core/src/node.rs
Refactor to remove collecting into a Vec, and more explicit handling of the different cases.
> perf: Remove unneeded allocations in NodeCost::get_cost

- coin-or-sys/build.rs
Rust 1.82 removed a linker option (`--whole-archive`) which has broken linking on Linux. This reorders the building / linking so that the linker finds the correct libraries.
See https://github.com/rust-lang/rust/pull/128400
> fix: Fix Rust 1.82 builds on Linux.

- Cargo.lock
- pywr-schema/Cargo.toml
Use a reference to Git repo until the next release is made. This removes a number of outdated dependencies.
> chore: Use latest svgbobdoc from main.

- pywr-core/src/metric.rs
- pywr-core/src/network.rs
- pywr-core/src/parameters/array.rs
- pywr-core/src/parameters/control_curves/piecewise.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/discount_factor.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/state.rs
- pywr-core/src/test_utils.rs
- pywr-core/src/timestep.rs
- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/edge.rs
- pywr-schema/src/error.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/nodes/mod.rs
- pywr-schema/src/parameters/aggregated.rs
- pywr-schema/src/parameters/asymmetric_switch.rs
- pywr-schema/src/parameters/control_curves.rs
- pywr-schema/src/parameters/indexed_array.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/python.rs
- pywr-schema/src/parameters/tables.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/src/visit.rs
`IndexMetric` mirrors `Metric`, but for integers.
Also adds support for:
- Integer arrays in core.
- `MultiValue<usize>` parameter return type.
Fixes #291
> feat: Replace DynamicIndexValue with IndexMetric 

- pywr-schema/src/error.rs
- pywr-schema/src/nodes/river_split_with_gauge.rs
- pywr-schema/tests/test_models.rs
- pywr-schema/tests/v1/river_split_with_gauge1-converted.json
- pywr-schema/tests/v1/river_split_with_gauge1.json
Add a conversion function for the factors on RiverSplitWithGauge. The factors have changed in this implementation and require conversion from ratios to proportions. This is only possible if they existing factors are all constants.
Fixes #241.
> fix: Try to convert RiverSplitWithGauge factors correctly.

- pywr-core/src/parameters/profiles/daily.rs
- pywr-core/src/parameters/profiles/rbf.rs
- pywr-core/src/timestep.rs
This matches the behaviour in v1
> fix: account for leap day when indexing daily profiles

- pywr-core/src/aggregated_node.rs
- pywr-core/src/lib.rs
- pywr-core/src/metric.rs
- pywr-core/src/network.rs
- pywr-core/src/parameters/aggregated_index.rs
- pywr-core/src/parameters/array.rs
- pywr-core/src/parameters/asymmetric.rs
- pywr-core/src/parameters/control_curves/index.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/indexed_array.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/parameters/py.rs
- pywr-core/src/parameters/rhai.rs
- pywr-core/src/parameters/threshold.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/state.rs
- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/nodes/core.rs
- pywr-schema/src/nodes/delay.rs
- pywr-schema/src/parameters/aggregated.rs
- pywr-schema/src/parameters/asymmetric_switch.rs
- pywr-schema/src/parameters/control_curves.rs
- pywr-schema/src/parameters/delay.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/profiles.rs
- pywr-schema/src/parameters/thresholds.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/src/visit.rs
U64 is more appropriate for data that should be the same across multiple platforms. `usize` is platform specific.
This does not change the use of `NonZeroUsize` for the rolling window size in virtual storage nodes. Ultimately this values is used to size an array and that maximum size will be platform dependent.
Currently there is some casting to `usize`. A separate update could warn on the `cast_lossless` lint and remove the use of `as` throughout.
One outstanding query is whether this should actually be i64 to support negative values?
Issue #291.
> feat: Use u64 instead of usize for index parameters.

- .github/workflows/linux.yml
- README.md
- pywr-core/Cargo.toml
- pywr-core/src/lib.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/solvers/builder.rs
- pywr-core/src/timestep.rs
- pywr-schema/Cargo.toml
- pywr-schema/src/error.rs
- pywr-schema/src/model.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/python.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/src/timeseries/pandas.rs
Adds a new default feature, `pyo3`, for enabling Python support. It is useful to feature gate PyO3 functionality to allow pywr-schema to built on a wider range of platforms (e.g. WASM).
This also updates the Linux CI to use cargo hack to check every feature combination is functional.
> feat: Add pyo3 feature for Python support.

- pywr-cli/src/main.rs
- pywr-core/src/solvers/cbc/settings.rs
- pywr-core/src/solvers/clp/settings.rs
- pywr-core/src/solvers/highs/settings.rs
- pywr-core/src/solvers/ipm_ocl/settings.rs
- pywr-core/src/solvers/ipm_simd/settings.rs
- pywr-python/src/lib.rs
- Add CBC to CLI
- Enable parallel / threads to be enable from CLI.
> fix: Improve builder implementation for solver settings

- pywr-core/src/lib.rs
- pywr-core/src/network.rs
- pywr-core/src/recorders/hdf.rs
Implement #[from] for the HDF5 error. This requires removing the `PartialEq` and `Eq` derives for `PywrError`, and adding a new error variant for HDF5 unicode conversion. This allows neater handling of HDF5 errors in core.
> feat: Improve HDF5 error handling in pywr-core.

- pywr-core/src/derived_metric.rs
- pywr-core/src/metric.rs
- pywr-core/src/network.rs
- pywr-core/src/parameters/control_curves/piecewise.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/discount_factor.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/test_utils.rs
- pywr-core/src/timestep.rs
- pywr-core/src/virtual_storage.rs
Derived metrics, such as proportional volume, must be recalculated at the start of the time-step if the volume has been reset. This ensures that parameters that depend on the proportional volume (e.g., control curve calculations) use the correct value after the volume is reset.
> fix: Fix calculation of proportional volume on VS nodes after reset.

- pywr-schema/src/timeseries/mod.rs
Avoids a 'chunked array is not contiguous' error during conversion.
> fix: rechunk polars df columns before conversion to ndarrys

- pywr-cli/src/main.rs
- pywr-core/src/models/multi.rs
- pywr-core/src/models/simple.rs
- pywr-core/src/network.rs
- pywr-core/src/solvers/cbc/settings.rs
- pywr-core/src/solvers/clp/settings.rs
- pywr-core/src/solvers/highs/settings.rs
- pywr-core/src/solvers/ipm_ocl/settings.rs
- pywr-core/src/solvers/ipm_simd/settings.rs
- pywr-core/src/solvers/mod.rs
- pywr-python/src/lib.rs
- pywr-schema/src/parameters/profiles.rs
Python extension was deadlocking because allow_threads() was not being called.
Also updates the IpmSimd solver settings to allow overriding the feature check.
> fix: Correctly use Python::allow_threads() to avoid deadlock.

- .github/workflows/linux.yml
- .github/workflows/windows.yml
- Cargo.lock
- Cargo.toml
- ipm-simd/Cargo.toml
- ipm-simd/src/common.rs
- ipm-simd/src/lib.rs
- ipm-simd/src/path_following_direct.rs
- pywr-cli/src/main.rs
- pywr-core/Cargo.toml
- pywr-core/benches/random_models.rs
- pywr-core/src/lib.rs
- pywr-core/src/solvers/ipm_ocl/mod.rs
- pywr-core/src/solvers/ipm_simd/mod.rs
- pywr-core/src/solvers/ipm_simd/settings.rs
- pywr-core/src/test_utils.rs
- pywr-python/src/lib.rs
- pywr-schema/tests/test_models.rs
This removes the need for the nightly Rust compiler to use the IPM SIMD solver. This is achieved, with safe code, by using the `wide` crate. However, it does mean that the solver is now not generic with regard the SIMD type and number of lanes. Instead it is now hard-coded to be f64x4.
> feat: Use wide crate for stable SIMD support.

- pywr-core/src/aggregated_node.rs
- pywr-core/src/metric.rs
- pywr-core/src/models/mod.rs
- pywr-core/src/network.rs
- pywr-core/src/parameters/aggregated.rs
- pywr-core/src/parameters/aggregated_index.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/parameters/rolling.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/scenario.rs
- pywr-core/src/test_utils.rs
- pywr-core/src/timestep.rs
- pywr-core/src/virtual_storage.rs
- pywr-schema/src/model.rs
- pywr-schema/src/parameters/aggregated.rs
- pywr-schema/src/parameters/delay.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/parameters/rolling.rs
Add a rolling parameter. Add a generic rolling parametr to core for use with f64 and u64 values. These two variants are also added to the schema.
Some additional trait implementations and test utility functions have been added to make this work. These mirror the f64 implementations.
One indexing bug is also corrected.
> feat: Add RollingParameter.

- .github/dependabot.yml
This avoids one dependency blocking the update of others. E.g. polars.
> chore: Remove groups from dependabot config.

- pywr-schema/src/error.rs
- pywr-schema/src/model.rs
- pywr-schema/src/nodes/annual_virtual_storage.rs
- pywr-schema/src/nodes/attributes.rs
- pywr-schema/src/nodes/core.rs
- pywr-schema/src/nodes/delay.rs
- pywr-schema/src/nodes/loss_link.rs
- pywr-schema/src/nodes/mod.rs
- pywr-schema/src/nodes/monthly_virtual_storage.rs
- pywr-schema/src/nodes/piecewise_link.rs
- pywr-schema/src/nodes/piecewise_storage.rs
- pywr-schema/src/nodes/reservoir.rs
- pywr-schema/src/nodes/river.rs
- pywr-schema/src/nodes/river_gauge.rs
- pywr-schema/src/nodes/river_split_with_gauge.rs
- pywr-schema/src/nodes/rolling_virtual_storage.rs
- pywr-schema/src/nodes/turbine.rs
- pywr-schema/src/nodes/virtual_storage.rs
- pywr-schema/src/nodes/water_treatment_works.rs
Use a macro to generate a private enum for each node that defines which variants of `NodeAttribute` are supported for this node. This improves the pattern matching in `create_metric`.
> refactor: Use private enums for node attributes.

- pywr-core/src/models/multi.rs
- pywr-core/src/models/simple.rs
- pywr-core/src/network.rs
Removes the use of a hashmap for accumulating component timing information.
Fixes #440.
> perf: Use indices instead of keys for tracking component timing.

- pywr-core/src/models/multi.rs
- pywr-core/src/models/simple.rs
- pywr-core/src/solvers/clp/mod.rs
- pywr-core/src/solvers/clp/settings.rs
- pywr-core/src/solvers/highs/mod.rs
- pywr-core/src/solvers/highs/settings.rs
- pywr-core/src/solvers/ipm_simd/mod.rs
- pywr-core/src/solvers/ipm_simd/settings.rs
- pywr-core/src/solvers/mod.rs
- pywr-python/pywr/__init__.py
- pywr-python/pywr/pywr.pyi
- pywr-python/src/lib.rs
- pywr-python/tests/models/multi1/model.json
- pywr-python/tests/models/multi1/network1.json
- pywr-python/tests/models/multi1/network2.json
- pywr-python/tests/test_models.py
- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/model.rs
- pywr-schema/src/timeseries/mod.rs
Refactor Python extension code to remove wrappers, and expose schema and model structs directly. Add MultiNetworkModel to the extension so these models can be run from Python.
> feat: Add multi-model to Python extension.

- pywr-schema/src/metric.rs
- pywr-schema/src/network.rs
- pywr-schema/src/parameters/control_curves.rs
- pywr-schema/src/v1.rs
This update converts it from a storage node reference to a metric reference. Some logic is also added to the v1 to v2 conversion to handle to determine if a node is virtual or not.
> fix: update storage attribute of ControlCurvePiecewiseInterpolatedParameter

- .github/dependabot.yml
This is for both cargo and uv.
> chore: Group patch updates together in dependabot.

- pywr-cli/src/main.rs
- pywr-schema/src/lib.rs
- pywr-schema/src/model.rs
- pywr-schema/src/network.rs
- pywr-schema/src/nodes/mod.rs
- pywr-schema/src/parameters/python.rs
- pywr-schema/tests/test_invalid.rs
More naming consistency. First between the models and their corresponding error types. Also rename `PywrNetwork` to `NetworkSchema` for consistency with the models. Also remove the prefix `Pywr` from some other structs.
> refactor: Rename various schema types and errors.
