- Cargo.toml
- src/main.rs
- src/model.rs
- src/python.rs
- src/solvers/mod.rs
Make the OpenCL clipm crate optional and non-default.
> feat: Add clipm feature.

- Cargo.toml
- src/schema/parameters/mod.rs
Include placeholders todo! for new parameters.
> chore: Update to pywr-schema 0.7.0

- Cargo.toml
- src/model.rs
- src/schema/data_tables/mod.rs
This is just a simple swap for the time being.
> feat: Use tracing instead of log.

- pywr-schema/Cargo.toml
- pywr-schema/src/error.rs
- pywr-schema/src/nodes/annual_virtual_storage.rs
- pywr-schema/src/nodes/core.rs
- pywr-schema/src/nodes/delay.rs
- pywr-schema/src/nodes/loss_link.rs
- pywr-schema/src/nodes/mod.rs
- pywr-schema/src/nodes/monthly_virtual_storage.rs
- pywr-schema/src/nodes/piecewise_link.rs
- pywr-schema/src/nodes/piecewise_storage.rs
- pywr-schema/src/nodes/river.rs
- pywr-schema/src/nodes/river_gauge.rs
- pywr-schema/src/nodes/river_split_with_gauge.rs
- pywr-schema/src/nodes/virtual_storage.rs
- pywr-schema/src/nodes/water_treatment_works.rs
- pywr-schema/src/parameters/mod.rs
- Add NodeType as a simple enum.
- Add NodeBuilder for constructing new nodes.
- Impl Default for Node schema
- Remove CustomNode; don't want to support this going forward.
> feat: Schema Node improvements.

- pywr-cli/src/main.rs
- pywr-core/benches/random_models.rs
- pywr-core/src/models/multi.rs
- pywr-core/src/parameters/constant.rs
- pywr-core/src/parameters/control_curves/mod.rs
- pywr-core/src/parameters/delay.rs
- pywr-core/src/parameters/discount_factor.rs
- pywr-core/src/parameters/interpolate.rs
- pywr-core/src/recorders/aggregator.rs
- pywr-core/src/recorders/csv.rs
- pywr-core/src/recorders/hdf.rs
- pywr-core/src/recorders/metric_set.rs
- pywr-core/src/recorders/mod.rs
- pywr-core/src/solvers/builder.rs
- pywr-core/src/solvers/clp/mod.rs
- pywr-core/src/solvers/clp/settings.rs
- pywr-core/src/state.rs
- pywr-core/src/test_utils.rs
- pywr-core/src/virtual_storage.rs
- pywr-python/src/lib.rs
Remove some warnings and dead code. These commits won't be squashed.
> Cargo fix and tidy up

- clp-sys/Cargo.toml
This reverts commit edb3679375534d98635924b1a01cf7e99338725a.
> Revert "chore: Disable parallel feature in cc crate (#120)"

- Cargo.toml
- pywr-core/src/parameters/py.rs
- pywr-python/src/lib.rs
- pywr-schema/src/parameters/python.rs
This updates includes a significant API change.
> chore: Upgrade to pyo3-0.21

- Cargo.toml
- pywr-schema/src/timeseries/align_and_resample.rs
This uses the new sorting API.
> feat: Upgrade polars to v0.39

- Cargo.toml
- pywr-cli/src/main.rs
- pywr-schema/src/model.rs
This uses the update pywr-v1-schema. The error handling in the convert command is also improved.
> feat: Add --network-only argument to CLI convert command

- .github/workflows/linux.yml
- .github/workflows/windows.yml
- pywr-schema/src/parameters/python.rs
Also add schema only build to CI.
> fix: Correctly feature gate PyO3 import.

- .github/workflows/linux.yml
- .github/workflows/windows.yml
- pywr-core/benches/random_models.rs
- pywr-core/src/parameters/constant.rs
- pywr-core/src/parameters/py.rs
- pywr-core/src/parameters/rhai.rs
- pywr-core/src/recorders/aggregator/mod.rs
- pywr-core/src/solvers/cbc/mod.rs
- pywr-core/src/virtual_storage.rs
This will need to be rebased until it passes.
> ci: Add clippy to Rust CI actions.

- pywr-core/src/recorders/metric_set.rs
- pywr-schema/src/error.rs
- pywr-schema/src/metric.rs
- pywr-schema/src/metric_sets/mod.rs
- pywr-schema/src/model.rs
These provide a convienient way to record metrics for all nodes and/or parameters in a model.
> feat: add filter options for metric sets

- pywr-core/src/network.rs
- pywr-core/src/solvers/builder.rs
- pywr-core/src/state.rs
- pywr-core/src/virtual_storage.rs
- Remove unused field `flow_constraints`.
- Make flow factors required and update the builder.
- Builder now provides unit factors if none are given.
- Improve API to return slice reference and iterator (removes some allocations).
> fix: Correct some issues with VirtualStorage node.

- Cargo.lock
- Cargo.toml
- pywr-cli/Cargo.toml
- pywr-core/Cargo.toml
- pywr-schema-macros/Cargo.toml
- pywr-schema/Cargo.toml
Remove specific patch versions for all dependencies. Make the rand and rand_chacha crates workspace versioned.
> chore(deps): General dependency update.

- pywr-schema/src/metric.rs
- pywr-schema/src/model.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/tests/test_models.rs
- pywr-schema/tests/v1/timeseries-converted.json
- pywr-schema/tests/v1/timeseries.json
Handle conversion of v1.x dataframe parameters that reference tables.
> fix: Fix converting dataframe parameters which reference tables.

- pywr-core/src/models/mod.rs
- pywr-core/src/models/multi.rs
- pywr-core/src/test_utils.rs
- pywr-schema/src/data_tables/mod.rs
- pywr-schema/src/error.rs
- pywr-schema/src/lib.rs
- pywr-schema/src/model.rs
- pywr-schema/src/network.rs
- pywr-schema/src/outputs/mod.rs
- pywr-schema/src/parameters/python.rs
- pywr-schema/src/timeseries/mod.rs
- pywr-schema/src/timeseries/pandas.rs
- pywr-schema/tests/test_invalid.rs
Improve the handling of errors during model building. This will provide more context information about which part and component of the build process failed.
In addition, it should pass the "cause" of the resulting exception as any underlying `PyErr` (e.g. from a custom parameter, or loading via pandas) if one exists.
> feat: Add new model and network level error types.

- pywr-schema/src/metric_sets/mod.rs
- pywr-schema/tests/reservoir-failure-levels1-expected.csv
- pywr-schema/tests/reservoir-failure-levels1.json
- pywr-schema/tests/test_models.rs
Tests that index metrics can be recorded and output.
Fixes #328
> feat: Add tests for recording index metric in metric set.

- .github/workflows/wheels.yml
Rename wheels workflow to something more useful.
> ci: Setup trusted publishing environment for Pypi.

- Cargo.lock
- Cargo.toml
- pywr-core/src/parameters/constant_scenario.rs
- pywr-core/src/parameters/mod.rs
- pywr-core/src/scenario.rs
- pywr-core/src/state.rs
- pywr-schema/src/error.rs
- pywr-schema/src/parameters/core.rs
- pywr-schema/src/parameters/mod.rs
- pywr-schema/tests/test_models.rs
- pywr-schema/tests/v1/scenarios-converted.json
- pywr-schema/tests/v1/scenarios.json
Also updates pywr-v1-schema to 0.21
> feat: add constant scenario parameter

- .github/workflows/deploy-book.yml
> ci: Deploy book workflow now needs a full checkout
